### ISSUE TITLE
Please add items to the README: UDP, and IPv6

### ISSUE THREAD

**Issue by BillDietrich** [GouveaHeitor/nipe#57]
Please add items to the README:

1- Does this route UDP traffic also, or just TCP ? https://2019.www.torproject.org/docs/faq.html.en#TransportIPnotTCP seems to say Tor doesn't do UDP.

2- Does this route IPv6 traffic also, or just IPv4 traffic ?

**Comment by sh1va73** [comment]
I also see that my IPv4 address is changed, but my IPv6 address is not changed.

**Comment by GouveaHeitor** [comment]
Hello guys,

This issue is very interesting!

Currently, the Nipe code only supports ipv4, but I can think of how to do for ipv6 too!

On the other question, only traffic other than DNS requests for local/loopback addresses is not passed by Tor. All non-local UDP/ICMP traffic is blocked.

Thank you very much for your attention!

**Comment by BillDietrich** [comment]
Thanks for the info.  Just a reminder: the request was to add that info to the README file.

**Comment by GouveaHeitor** [comment]
I just did this in commit fd9728c
A issue for us to work on ipv6 support has been opened, it's here: #59 

Thanks guys!
