### ISSUE TITLE
Nipe and vpn

### ISSUE THREAD

**Issue by karencho777** [GouveaHeitor/nipe#72]
Hello, how do I set up to use VPN and then over the VPN use NIPE?

**Comment by karencho777** [comment]
it can be possible!!! I did it via simple Gnome Vpn connection option

**Comment by bmeneguele** [comment]
Hi @karencho777,

as far as I can see it shouldn't be a problem indeed. You may have some troubles to establish the VPN connection itself, since some may block you from connecting based on IP or something like that. But once it is connected the firewall rules set up by nipe should be enough to redirect your packets through Tor.

It basically depends on how your VPN server is configured.

**Comment by lillstrumpa** [comment]
1. lets say I connect with VPN ( openvpn ) in linux (VM) and then run nipe after, is nipe running inside the connection or do it bypass it somehow.
2. lets say I connect with VPN on my host computer(windows box) ( in NAT mode) then run nipe on the linux dist( VM) is it working inside the tunnel run by the windows box ?

just some thoughts...

**Comment by GouveaHeitor** [comment]
Hi @karencho777,

Just to complement the response from our friend @bmeneguele, the best scenario I can imagine using Nipe with a VPN service is as follows:

- You can create a connection to your VPN (using OpenVPN for example), created on a server under your ownership where NIPE is running and redirecting your traffic to the TOR Network.

Thx!
