### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by GouveaHeitor** [GouveaHeitor/nipe#81]
It is not from today that Nipe suffers several problems regarding compatibility with various linux distributions, thinking of that, I decided to start a refactoring in the current code.

The new code will try to follow the good practices of Clean Code, in addition to adopting this [Style Guide](https://github.com/GouveaHeitor/perl-style-guide), and will adopt an architecture standard based on [Flow-Based Programming](https://en.wikipedia.org/wiki/Flow-based_programming).

In addition, I will endeavor to stop using command execution directly on the system, thus using genuine code.

I believe this will help resolve compatibility issues.

Any other suggestions are very welcome and should be commented below.

**Comment by GouveaHeitor** [comment]
Others issues will open during this process, however all will be referenced here.
Example issue #82.

**Comment by bmeneguele** [comment]
@GouveaHeitor I think issue #86 can be added to the "maintenance" project and part of this issue here.

**Comment by GouveaHeitor** [comment]
Thx @bmeneguele!

**Comment by velrino** [comment]
I don't know PERL, but some things that I believe are good practices for your project

I put it below the comment 
/************* suggestion *************/

**In Functions.pm**
https://pastebin.com/rTHudAzD

**In Device.pm**
https://pastebin.com/skHtdECA

**Comment by GouveaHeitor** [comment]
Hi @velrino,

I took a look at your code and found your recommendations interesting and they are very valid.

I will understand a little better about how I can implement this without impacting the new features that we are going to publish soon.

Thank you very much for the recommendation and feel free to suggest other improvements!

Thx

**Comment by bmeneguele** [comment]
@GouveaHeitor, I noticed that the last three or four suggestion for code changes were always based on `master` branch, what do you think if we change CONTRIBUTING file stating the changes should be done against `develop` branch?

At the same time, do you have any suggestion for *line length limit* ? Should Nipe's code and documentation be limited to 80, 100, 120, .. columns? I personally prefer 80 chars since it fits pretty well on 15" monitors (laptop) or bigger ones with multiple windows open.
