### ISSUE TITLE
ping: sendmsg: Operation not permitted

### ISSUE THREAD

**Issue by erfan4lx** [GouveaHeitor/nipe#89]
Hi friends

I after run the nipe.pl
And enter the ping example
ping google.com

got this error:
PING google.com (172.217.20.78) 56(84) bytes of data.
From erfan4lx (192.168.1.105) icmp_seq=1 Destination Port Unreachable

If you know why?!, Please help me thanks

**Comment by bmeneguele** [comment]
Hi @erfan4lx, that's not an issue actually:

```
iptables -t filter -A OUTPUT -p icmp -j REJECT
```

we intentionally prevent ICMP (the type of package sent by `ping`) packages from being sent out from your machine. ICMP packages are neither TCP nor UDP and not even need a specific port to work. And at the same time, the way it works completely break your anonymity in the network, _n_ packages are sent to the network with your "source address" as a plain text number until it reaches the target: if you are 3 hops from destination it will send 3 packages to get there.

That's why Nipe blocks ICMP from getting out of your machine.

**Comment by GouveaHeitor** [comment]
Thx @bmeneguele by the answer.

In the "README" there is a warning about this. As the question was answered, I am closing this issue.

Thx
